"""
routes/ai_explain.py — IBM watsonx AI explanation endpoint.

Route:
  POST /ai/explain  — accepts a FatigueResult, returns a natural-language
                      explanation generated by IBM watsonx.ai.

The scoring engine is never called here. AI only interprets an existing score.
"""

from fastapi import APIRouter
from pydantic import BaseModel

from app.models.fatigue import FatigueResult
from app.engine.ai_explain import explain_score

router = APIRouter(prefix="/ai", tags=["AI Explanation (IBM watsonx)"])


class ExplainResponse(BaseModel):
    astronaut_id: str
    fatigue_score: float
    risk_level: str
    explanation: str
    disclaimer: str = (
        "This AI-generated explanation is for informational purposes only. "
        "It does NOT constitute a medical diagnosis. "
        "Final decisions must be made by qualified human personnel."
    )


@router.post(
    "/explain",
    response_model=ExplainResponse,
    summary="AI Explanation of Fatigue Score (IBM watsonx)",
    description=(
        "Accepts a previously computed FatigueResult and returns a "
        "natural-language explanation from IBM watsonx.ai. "
        "**The AI does not recalculate or override the score.** "
        "Set `WATSONX_API_KEY` and `WATSONX_PROJECT_ID` env vars to activate."
    ),
)
def explain(result: FatigueResult) -> ExplainResponse:
    """
    POST /ai/explain

    Passes the already-computed FatigueResult to the watsonx explanation
    engine and returns a human-readable narrative. The numeric score is
    never touched here.
    """
    explanation_text = explain_score(result)
    return ExplainResponse(
        astronaut_id=result.astronaut_id,
        fatigue_score=result.fatigue_score,
        risk_level=result.risk_level,
        explanation=explanation_text,
    )
